[package]
name = "minesweeper-bevy"
version = "0.1.0"
authors = ["yetanothercheer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4.0"

rand = "0.8.1"
log = "0.4.0"
env_logger = "0.8.2"
